CREATE DATABASE finance_tracker;
USE finance_tracker;

CREATE TABLE users(
	user_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    user_password CHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE = INNODB;

CREATE TABLE accounts(
	account_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    account_name VARCHAR(50) NOT NULL,
    currency VARCHAR(50) NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_account_user` FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE RESTRICT
)ENGINE = INNODB;

CREATE TABLE transactions(
	transaction_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    transaction_description VARCHAR(50) NOT NULL,
    amount INT UNSIGNED NOT NULL,
    is_income BOOLEAN NOT NULL,
    account_id INT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT `fk_transaction_account` FOREIGN KEY (account_id) REFERENCES accounts(account_id) ON UPDATE CASCADE ON DELETE RESTRICT
)ENGINE = INNODB;